# Configuration file for training a pretrained (generator) SRGAN model.

experiment_name: 'SRESNET/training_V1'
model_type: 'SRESNET'
from_pretrained: False
task: 'train'  # in ('train', 'test', 'predict')

train:
  crop_size: 96

paths:
  model_save: '../../../models/super_resolution/'
  train_set: '../../../data/raw/train'
  val_set: '../../../data/raw/val'
  val_images_save: '../../../data/processed/val/'

hyperparameters:
  batch_size: 32
  epochs: 262
  learning_rate: 0.0001
