version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: >  # Download models with authentification, and run main script
        sh -c "dvc pull models/super_resolution/SRGAN/ssh_V2/generator_epoch_104.torch &&
               cd app &&
               streamlit run main.py"
    ports:
      - "8000:5000"  # mapping of <Host>:<Container> ports.  => http://localhost:8880/
    ipc: host  # Increase the shared memory size for the container
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
  test:
    image: nvidia/cuda:11.3.0-base
    command: nvidia-smi
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
