version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: >  # Download models with authentification, and run main script
      sh -c "dvc pull models &&
             cd app &&
             streamlit run main.py"
    volumes:  #TODO remove volume
      - ../api/app/predictions:/app/predictions
    ports:
      - "5000:5000"  # mapping of <Host>:<Container> ports.
    ipc: host  # Increase the shared memory size for the container
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
  test:
    image: nvidia/cuda:11.3.0-base
    command: nvidia-smi
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
