# Configuration file for training a pretrained (generator) SRGAN model.

experiment_name: 'SRGAN_training_V1'
model_type: 'SRGAN'
from_pretrained: 'True' # Use the pretrained generator model.
task: 'train'  # in ('train', 'evaluate', 'predict')

paths:
  #TODO add all training parameters to use **config["train_parameters"]. Put full paths.

  # Paths
  model_save_folder: '../../../models/super_resolution/'

  train_images_input_path: '../../../data/raw/train'
  val_images_input_path: '../../../data/raw/val'
  test_images_input_path: '../../../data/raw/test'

  val_images_save_folder: '../../../data/processed/val/'
  test_images_save_folder: '../../../data/processed/test/'

hyperparameters:
  batch_size: 32
  epochs: 52
  learning_rate: 0.0001
